server:
  port: 8001

spring:
  application:
    name: cloud-payment-HYSTRIX-PAYMENT

eureka:
  client:
    #注册进Eurekaservice
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment-hystrix8001
    prefer-ip-address: true